version: '3'
services:
  db:
    image: "db-proj001:0.1"
    container_name: "proj001"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=projeto001
    networks:
      dockernet:
        ipv4_address: 172.20.1.2

  api-proj001:
    image: "api_proj001:0.3"
    container_name: "api-proj001"
    ports:
      - "8002:8000"
    networks:
      dockernet:
        ipv4_address: 172.20.1.3

networks:
  #dc1:
  dockernet:
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24